### Inserir dados no banco
POST http://127.0.0.1:8000/api/marca
Content-Type: application/x-www-form-urlencoded

nome=Hyundai&imagem=hyundai_logo.png

### Mostra todas os dados do banco

GET http://127.0.0.1:8000/api/modelo?atributos=nome,numero_portas,marca_id&atributos_marca=nome&filtro=abs:=:1;numero_portas:=:4

### Mostra um dado especifico do banco

GET http://127.0.0.1:8000/api/marca/6

### Atualiza um dado especifico do banco

PUT http://127.0.0.1:8000/api/marca/7
Content-Type: application/x-www-form-urlencoded

nome=Mercedes%20-%20Teste&imagem=logo_mercedes.jpeg

### Deleta um dado especifico do banco

DELETE http://127.0.0.1:8000/api/marca/8

### Enviando uma imagem para marca

POST http://127.0.0.1:8000/api/marca
Accept: application/json
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary

------WebKitFormBoundary
Content-Disposition: form-data; name="nome"

Hyundai
------WebKitFormBoundary
Content-Disposition: form-data; name="imagem"; filename="ford.png"
Content-Type: image/png

< C:/Users/vitor.pereira/Desktop/imagens_marcas/hyundai.png
------WebKitFormBoundary--

### Buscando imagem

GET  http://127.0.0.1:8000/storage/imagens\/Wl03kpdqYTqTyypWpBTJpZ0NSOexHl7FDdUTdIMv.png


### Atualizar uma imagem e todas as infos

POST  http://127.0.0.1:8000/api/marca/1
Accept: application/json
X-HTTP-Method-Override: PUT
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary

------WebKitFormBoundary
Content-Disposition: form-data; name="nome"

BMW
------WebKitFormBoundary
Content-Disposition: form-data; name="imagem"; filename="hyundai.png"
Content-Type: image/png

< C:/Users/vitor.pereira/Desktop/imagens_marcas/bmw.png
------WebKitFormBoundary--

### Enviando uma imagem para modelo

POST http://127.0.0.1:8000/api/modelo
Accept: application/json
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary123456

------WebKitFormBoundary123456
Content-Disposition: form-data; name="marca_id"

2
------WebKitFormBoundary123456
Content-Disposition: form-data; name="nome"

Hyundai HB20s 1.0
------WebKitFormBoundary123456
Content-Disposition: form-data; name="imagem"; filename="ford.png"
Content-Type: image/png

< C:\Users\vitor.pereira\Desktop\imagens_modelos\hyundai_hb20s_1_0.png
------WebKitFormBoundary123456
Content-Disposition: form-data; name="numero_portas"

5
------WebKitFormBoundary123456
Content-Disposition: form-data; name="lugares"

5
------WebKitFormBoundary123456
Content-Disposition: form-data; name="air_bag"

0
------WebKitFormBoundary123456
Content-Disposition: form-data; name="abs"

1
------WebKitFormBoundary123456--

### Mostra todas os dados do banco modelo

GET http://127.0.0.1:8000/api/modelo

### Atualizar uma imagem do modelo e todas suas informações

POST  http://127.0.0.1:8000/api/modelo/12
Accept: application/json
X-HTTP-Method-Override: PUT
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary123456

------WebKitFormBoundary123456
Content-Disposition: form-data; name="marca_id"

1
------WebKitFormBoundary123456
Content-Disposition: form-data; name="nome"

Ford KA Sedan 1.0
------WebKitFormBoundary123456
Content-Disposition: form-data; name="imagem"; filename="ford.png"
Content-Type: image/png

< C:\Users\vitor.pereira\Desktop\imagens_modelos\ford_ka_sedan_1_0.png
------WebKitFormBoundary123456
Content-Disposition: form-data; name="numero_portas"

4
------WebKitFormBoundary123456
Content-Disposition: form-data; name="lugares"

5
------WebKitFormBoundary123456
Content-Disposition: form-data; name="air_bag"

1
------WebKitFormBoundary123456
Content-Disposition: form-data; name="abs"

1
------WebKitFormBoundary123456--

### Atualizando apenas a imagem de marca
POST  http://127.0.0.1:8000/api/marca/1
Accept: application/json
X-HTTP-Method-Override: PATCH
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary

------WebKitFormBoundary
Content-Disposition: form-data; name="imagem"; filename="hyundai.png"
Content-Type: image/png

< C:/Users/vitor.pereira/Desktop/imagens_marcas/ford.png
------WebKitFormBoundary--

### Atualizar uma imagem do modelo e todas suas informações

POST  http://127.0.0.1:8000/api/modelo/12
Accept: application/json
X-HTTP-Method-Override: PATCH
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary123456

------WebKitFormBoundary123456
Content-Disposition: form-data; name="imagem"; filename="ford.png"
Content-Type: image/png

< C:\Users\vitor.pereira\Desktop\imagens_modelos\ford_ka_sedan_1_0.png
------WebKitFormBoundary123456--